const {chromium} = require(process.env.CODEX_NODE_MODULES + '/playwright');
const fs = require('fs');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:50123/',{waitUntil:'domcontentloaded'});
 await page.locator('#pageLoader').waitFor({state:'detached',timeout:15000});
 await page.screenshot({path:'test-environment/artifacts/home-desktop.jpg',quality:65,fullPage:true});
 await page.getByRole('button',{name:'开始刷题',exact:false}).first().click();
 await page.screenshot({path:'test-environment/artifacts/practice-desktop.jpg',quality:65,fullPage:true});
 await page.evaluate(()=>switchPage('import'));
 await page.locator('#file-input').setInputFiles({name:'回归题库.txt',mimeType:'text/plain',buffer:Buffer.from('一、单项选择题\n1、测试题（A）\nA.甲\nB.乙\n二、多项选择题\n2、多选题（AC）\nA.甲\nB.乙\nC.丙\n三、判断题\n3、判断题（对）')});
 await page.locator('#bank-name').fill('验证题库');
 await page.locator('#import-btn').click();
 await page.waitForFunction(()=>document.getElementById('import-result').textContent.includes('成功导入'));
 console.log('IMPORT:',await page.locator('#import-result').innerText());
 await page.evaluate(()=>switchPage('practice'));
 await page.waitForFunction(()=>document.querySelector('#practice-bank').options.length>1);
 await page.selectOption('#practice-bank','验证题库');
 await page.fill('#practice-single-count','1');await page.fill('#practice-multi-count','1');await page.fill('#practice-judge-count','1');
 await page.evaluate(()=>startPractice(true));
 console.log('QUESTIONS:',await page.evaluate(()=>practiceQuestions.length));
 await page.screenshot({path:'test-environment/artifacts/question-desktop.jpg',quality:65,fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'test-environment/artifacts/question-mobile.jpg',quality:65,fullPage:true});
 await page.evaluate(()=>switchPage('dashboard'));
 await page.screenshot({path:'test-environment/artifacts/home-mobile.jpg',quality:65,fullPage:true});
 console.log('OVERFLOW:',await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));
 console.log('PAGE_ERRORS:',errors);
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
